FROM busybox:latest

# Create directory for the website
RUN mkdir /www

# Copy the index.html file into the container
COPY index.html /www/index.html

# Expose port 8000
ENV PORT=8000
EXPOSE ${PORT}

# Start the web server
CMD ["sh", "-c", "httpd -f -p ${PORT} -h /www"]